var searchData=
[
  ['c_20and_20dlls_20to_20modify_20incoming_20data_20in_20an_20input_20port_0',['An example which shows how to use C++ and DLLS to modify incoming data in an input port',['../group__portmonitors__examples__5.html',1,'']]],
  ['carrier_1',['Gstreamer carrier',['../group__carrier__gstreamer__howto.html',1,'']]],
  ['carriers_2',['carriers',['../group__carriers__lists.html',1,'Available Carriers'],['../group__carriers__module.html',1,'Carriers'],['../group__carrier__config__mpi.html',1,'mpi carriers']]],
  ['carriers_20for_20new_20kinds_20of_20connections_3',['Creating carriers for new kinds of connections',['../group__carrier__expert.html',1,'']]],
  ['check_20yarp_20configuration_4',['yarp-config: utility to check yarp configuration',['../group__yarp-config.html',1,'']]],
  ['classes_5',['classes',['../group__key__class.html',1,'Basic Classes'],['../group__comm__class.html',1,'Communication Classes'],['../group__sig__class.html',1,'yarp::sig  classes']]],
  ['client_20architecture_6',['Network Wrapper Server and Network Wrapper Client Architecture',['../group__nws__and__nwc__architecture.html',1,'']]],
  ['client_20configurations_7',['FrameTransform: possibile server-client configurations',['../group__Fts__ftc__config.html',1,'']]],
  ['clients_20clients_20pre_20nwc_20nws_20architecture_8',['Network Clients (Clients - pre NWC/NWS architecture)',['../group__dev__impl__network__clients.html',1,'']]],
  ['clients_20nwc_9',['clients nwc',['../group__dev__impl__nwc__ros2.html',1,'ROS2 Network Wrapper Clients (NWC)'],['../group__dev__impl__nwc__yarp.html',1,'YARP Network Wrapper Clients (NWC)']]],
  ['cmake_20tutorial_3a_20how_20to_20add_20a_20device_20to_20yarp_10',['CMake tutorial: how to add a device to YARP',['../group__add__a__device.html',1,'']]],
  ['code_20generator_20compiler_20for_20parameters_20parsers_11',['yarpDeviceParamParserGenerator: YARP code generator/compiler for parameters parsers',['../group__yarpDeviceParamParserGenerator.html',1,'']]],
  ['code_20generator_20compiler_20for_20thrift_20idl_12',['yarpidl_thrift: YARP code generator/compiler for Thrift IDL',['../group__yarpidl__thrift.html',1,'']]],
  ['command_20line_20interface_13',['yarp: the main command-line interface',['../group__yarp.html',1,'']]],
  ['common_20nws_20nwc_20architectures_14',['Examples of common NWS/NWC Architectures',['../group__nws__and__nwc__examples.html',1,'']]],
  ['communication_20classes_15',['Communication Classes',['../group__comm__class.html',1,'']]],
  ['compile_20yarp_20plugins_16',['Ways to compile YARP plugins',['../group__compile__yarp__plugins.html',1,'']]],
  ['compiler_20for_20parameters_20parsers_17',['yarpDeviceParamParserGenerator: YARP code generator/compiler for parameters parsers',['../group__yarpDeviceParamParserGenerator.html',1,'']]],
  ['compiler_20for_20thrift_20idl_18',['yarpidl_thrift: YARP code generator/compiler for Thrift IDL',['../group__yarpidl__thrift.html',1,'']]],
  ['config_3a_20utility_20to_20check_20yarp_20configuration_19',['yarp-config: utility to check yarp configuration',['../group__yarp-config.html',1,'']]],
  ['configuration_20',['configuration',['../group__dev__class.html',1,'Device Creation/Configuration'],['../group__yarp-config.html',1,'yarp-config: utility to check yarp configuration']]],
  ['configurations_21',['FrameTransform: possibile server-client configurations',['../group__Fts__ftc__config.html',1,'']]],
  ['configuring_20yarp_20connections_22',['Configuring YARP Connections',['../group__carrier__config.html',1,'']]],
  ['connection_20to_20encode_20and_20decode_20data_23',['An example of using the portmonitor object at the both sides of a connection to encode and decode data',['../group__portmonitors__examples__3.html',1,'']]],
  ['connections_24',['connections',['../group__portmonitors__examples__1.html',1,'An example of using port monitors for arbitrating multiple connections'],['../group__carrier__config.html',1,'Configuring YARP Connections'],['../group__carrier__expert.html',1,'Creating carriers for new kinds of connections'],['../group__yarpconnectionsinfo.html',1,'yarpconnectionsinfo: A tool to display YARP ports and connections']]],
  ['console_25',['yarp: yarpdataplayer-console',['../group__yarpdataplayer-console.html',1,'']]],
  ['console_3a_20run_20and_20manage_20multiple_20programs_20on_20a_20set_20of_20machines_26',['yarpmanager-console: run and manage multiple programs on a set of machines',['../group__yarpmanager-console.html',1,'']]],
  ['console_3a_20visualize_20log_20from_20yarp_20programs_27',['yarplogger-console: visualize log from YARP programs',['../group__yarplogger-console.html',1,'']]],
  ['content_20of_20a_20port_28',['yarpscope: visualize the numerical content of a port',['../group__yarpscope.html',1,'']]],
  ['control_20the_20mobile_20base_20of_20the_20robot_29',['yarpmobilebasegui: Control the mobile base of the robot',['../group__yarpmobilebasegui.html',1,'']]],
  ['controls_20a_20llm_20device_30',['yarpllmgui: Controls a LLM device',['../group__yarpllmgui.html',1,'']]],
  ['controls_20the_20playback_20recording_20of_20an_20audio_20device_31',['yarpaudiocontrolgui: Controls the playback/recording of an audio device',['../group__yarpaudiocontrolgui.html',1,'']]],
  ['create_20a_20new_20data_20type_20in_20a_20port_32',['An example which shows how to use a Lua script to create a new data type in a port',['../group__portmonitors__examples__7.html',1,'']]],
  ['creating_20carriers_20for_20new_20kinds_20of_20connections_33',['Creating carriers for new kinds of connections',['../group__carrier__expert.html',1,'']]],
  ['creation_20configuration_34',['Device Creation/Configuration',['../group__dev__class.html',1,'']]]
];
