var ISpeechSynthesizerMsgs_8cpp =
[
    [ "ISpeechSynthesizerMsgs_getRemoteProtocolVersion_helper", "classISpeechSynthesizerMsgs__getRemoteProtocolVersion__helper.html", "classISpeechSynthesizerMsgs__getRemoteProtocolVersion__helper" ],
    [ "ISpeechSynthesizerMsgs_set_language_helper", "classISpeechSynthesizerMsgs__set__language__helper.html", "classISpeechSynthesizerMsgs__set__language__helper" ],
    [ "ISpeechSynthesizerMsgs_set_language_helper::Command", "classISpeechSynthesizerMsgs__set__language__helper_1_1Command.html", "classISpeechSynthesizerMsgs__set__language__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_set_language_helper::Reply", "classISpeechSynthesizerMsgs__set__language__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__set__language__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_get_language_helper", "classISpeechSynthesizerMsgs__get__language__helper.html", "classISpeechSynthesizerMsgs__get__language__helper" ],
    [ "ISpeechSynthesizerMsgs_get_language_helper::Command", "classISpeechSynthesizerMsgs__get__language__helper_1_1Command.html", "classISpeechSynthesizerMsgs__get__language__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_get_language_helper::Reply", "classISpeechSynthesizerMsgs__get__language__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__get__language__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_set_voice_helper", "classISpeechSynthesizerMsgs__set__voice__helper.html", "classISpeechSynthesizerMsgs__set__voice__helper" ],
    [ "ISpeechSynthesizerMsgs_set_voice_helper::Command", "classISpeechSynthesizerMsgs__set__voice__helper_1_1Command.html", "classISpeechSynthesizerMsgs__set__voice__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_set_voice_helper::Reply", "classISpeechSynthesizerMsgs__set__voice__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__set__voice__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_get_voice_helper", "classISpeechSynthesizerMsgs__get__voice__helper.html", "classISpeechSynthesizerMsgs__get__voice__helper" ],
    [ "ISpeechSynthesizerMsgs_get_voice_helper::Command", "classISpeechSynthesizerMsgs__get__voice__helper_1_1Command.html", "classISpeechSynthesizerMsgs__get__voice__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_get_voice_helper::Reply", "classISpeechSynthesizerMsgs__get__voice__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__get__voice__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_set_speed_helper", "classISpeechSynthesizerMsgs__set__speed__helper.html", "classISpeechSynthesizerMsgs__set__speed__helper" ],
    [ "ISpeechSynthesizerMsgs_set_speed_helper::Command", "classISpeechSynthesizerMsgs__set__speed__helper_1_1Command.html", "classISpeechSynthesizerMsgs__set__speed__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_set_speed_helper::Reply", "classISpeechSynthesizerMsgs__set__speed__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__set__speed__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_get_speed_helper", "classISpeechSynthesizerMsgs__get__speed__helper.html", "classISpeechSynthesizerMsgs__get__speed__helper" ],
    [ "ISpeechSynthesizerMsgs_get_speed_helper::Command", "classISpeechSynthesizerMsgs__get__speed__helper_1_1Command.html", "classISpeechSynthesizerMsgs__get__speed__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_get_speed_helper::Reply", "classISpeechSynthesizerMsgs__get__speed__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__get__speed__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_set_pitch_helper", "classISpeechSynthesizerMsgs__set__pitch__helper.html", "classISpeechSynthesizerMsgs__set__pitch__helper" ],
    [ "ISpeechSynthesizerMsgs_set_pitch_helper::Command", "classISpeechSynthesizerMsgs__set__pitch__helper_1_1Command.html", "classISpeechSynthesizerMsgs__set__pitch__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_set_pitch_helper::Reply", "classISpeechSynthesizerMsgs__set__pitch__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__set__pitch__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_get_pitch_helper", "classISpeechSynthesizerMsgs__get__pitch__helper.html", "classISpeechSynthesizerMsgs__get__pitch__helper" ],
    [ "ISpeechSynthesizerMsgs_get_pitch_helper::Command", "classISpeechSynthesizerMsgs__get__pitch__helper_1_1Command.html", "classISpeechSynthesizerMsgs__get__pitch__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_get_pitch_helper::Reply", "classISpeechSynthesizerMsgs__get__pitch__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__get__pitch__helper_1_1Reply" ],
    [ "ISpeechSynthesizerMsgs_synthesize_helper", "classISpeechSynthesizerMsgs__synthesize__helper.html", "classISpeechSynthesizerMsgs__synthesize__helper" ],
    [ "ISpeechSynthesizerMsgs_synthesize_helper::Command", "classISpeechSynthesizerMsgs__synthesize__helper_1_1Command.html", "classISpeechSynthesizerMsgs__synthesize__helper_1_1Command" ],
    [ "ISpeechSynthesizerMsgs_synthesize_helper::Reply", "classISpeechSynthesizerMsgs__synthesize__helper_1_1Reply.html", "classISpeechSynthesizerMsgs__synthesize__helper_1_1Reply" ]
];