var searchData=
[
  ['a_20connection_20to_20encode_20and_20decode_20data_0',['An example of using the portmonitor object at the both sides of a connection to encode and decode data',['../group__portmonitors__examples__3.html',1,'']]],
  ['a_20device_20to_20yarp_1',['How to add a device to YARP',['../group__add__a__device.html',1,'']]],
  ['a_20graphical_20tool_20for_20profiling_20and_20visualizing_20yarp_20network_2',['yarpviz: a graphical tool for profiling and visualizing YARP network',['../group__yarpviz.html',1,'']]],
  ['a_20laser_20scanner_3',['yarplaserscannergui: visualize data from a laser scanner',['../group__yarplaserscannergui.html',1,'']]],
  ['a_20llm_20device_4',['yarpllmgui: Controls a LLM device',['../group__yarpllmgui.html',1,'']]],
  ['a_20lua_20script_20to_20create_20a_20new_20data_20type_20in_20a_20port_5',['An example which shows how to use a Lua script to create a new data type in a port',['../group__portmonitors__examples__7.html',1,'']]],
  ['a_20lua_20script_20to_20modify_20image_20data_6',['An example which shows how to use a Lua script to modify image data',['../group__portmonitors__examples__4.html',1,'']]],
  ['a_20lua_20script_20to_20modify_20incoming_20data_20in_20an_20input_20port_7',['An example which shows how to use a Lua script to modify incoming data in an input port',['../group__portmonitors__examples__6.html',1,'']]],
  ['a_20plugin_20to_20yarp_8',['Add a plugin to YARP',['../group__add__a__plugin.html',1,'']]],
  ['a_20port_9',['yarpscope: visualize the numerical content of a port',['../group__yarpscope.html',1,'']]],
  ['a_20robot_10',['yarpmotorgui: move the joints of a robot',['../group__yarpmotorgui.html',1,'']]],
  ['a_20set_20of_20machines_11',['a set of machines',['../group__yarpmanager-console.html',1,'yarpmanager-console: run and manage multiple programs on a set of machines'],['../group__yarpmanager.html',1,'yarpmanager: edit, run and manage multiple programs on a set of machines'],['../group__yarprun.html',1,'yarprun: run programs on a set of machines']]],
  ['a_20tool_20to_20display_20yarp_20ports_20and_20connections_12',['yarpconnectionsinfo: A tool to display YARP ports and connections',['../group__yarpconnectionsinfo.html',1,'']]],
  ['about_20devices_13',['Tutorials and Examples about Devices',['../group__dev__tutorials.html',1,'']]],
  ['add_20a_20device_20to_20yarp_14',['How to add a device to YARP',['../group__add__a__device.html',1,'']]],
  ['add_20a_20plugin_20to_20yarp_15',['Add a plugin to YARP',['../group__add__a__plugin.html',1,'']]],
  ['all_20the_20required_20devices_20needed_20for_20transforming_20frames_16',['FrameTransform: start all the required devices needed for transforming frames',['../group__FrameTransform.html',1,'']]],
  ['an_20audio_20device_17',['yarpaudiocontrolgui: Controls the playback/recording of an audio device',['../group__yarpaudiocontrolgui.html',1,'']]],
  ['an_20example_20of_20using_20port_20arbitrator_20with_20time_20events_18',['An example of using port arbitrator with time events',['../group__portmonitors__examples__2.html',1,'']]],
  ['an_20example_20of_20using_20port_20monitors_20for_20arbitrating_20multiple_20connections_19',['An example of using port monitors for arbitrating multiple connections',['../group__portmonitors__examples__1.html',1,'']]],
  ['an_20example_20of_20using_20the_20portmonitor_20object_20at_20the_20both_20sides_20of_20a_20connection_20to_20encode_20and_20decode_20data_20',['An example of using the portmonitor object at the both sides of a connection to encode and decode data',['../group__portmonitors__examples__3.html',1,'']]],
  ['an_20example_20which_20shows_20how_20to_20use_20a_20lua_20script_20to_20create_20a_20new_20data_20type_20in_20a_20port_21',['An example which shows how to use a Lua script to create a new data type in a port',['../group__portmonitors__examples__7.html',1,'']]],
  ['an_20example_20which_20shows_20how_20to_20use_20a_20lua_20script_20to_20modify_20image_20data_22',['An example which shows how to use a Lua script to modify image data',['../group__portmonitors__examples__4.html',1,'']]],
  ['an_20example_20which_20shows_20how_20to_20use_20a_20lua_20script_20to_20modify_20incoming_20data_20in_20an_20input_20port_23',['An example which shows how to use a Lua script to modify incoming data in an input port',['../group__portmonitors__examples__6.html',1,'']]],
  ['an_20example_20which_20shows_20how_20to_20use_20c_20and_20dlls_20to_20modify_20incoming_20data_20in_20an_20input_20port_24',['An example which shows how to use C++ and DLLS to modify incoming data in an input port',['../group__portmonitors__examples__5.html',1,'']]],
  ['an_20utility_20to_20replay_20robot_20movements_25',['yarpactionsplayer: an utility to replay robot movements',['../group__yarpactionsplayer.html',1,'']]],
  ['an_20xml_20file_26',['yarprobotinterface: Start multiple YARP devices as specified in an xml file.',['../group__yarprobotinterface.html',1,'']]],
  ['analog_20sensor_20interfaces_27',['Multiple Analog Sensor Interfaces',['../group__dev__iface__multiple__analog.html',1,'']]],
  ['analog_20sensors_28',['Analog Sensors',['../group__dev__impl__analog__sensors.html',1,'']]],
  ['and_20connections_29',['yarpconnectionsinfo: A tool to display YARP ports and connections',['../group__yarpconnectionsinfo.html',1,'']]],
  ['and_20decode_20data_30',['An example of using the portmonitor object at the both sides of a connection to encode and decode data',['../group__portmonitors__examples__3.html',1,'']]],
  ['and_20dlls_20to_20modify_20incoming_20data_20in_20an_20input_20port_31',['An example which shows how to use C++ and DLLS to modify incoming data in an input port',['../group__portmonitors__examples__5.html',1,'']]],
  ['and_20examples_20about_20devices_32',['Tutorials and Examples about Devices',['../group__dev__tutorials.html',1,'']]],
  ['and_20manage_20multiple_20programs_20on_20a_20set_20of_20machines_33',['and manage multiple programs on a set of machines',['../group__yarpmanager-console.html',1,'yarpmanager-console: run and manage multiple programs on a set of machines'],['../group__yarpmanager.html',1,'yarpmanager: edit, run and manage multiple programs on a set of machines']]],
  ['and_20network_20wrapper_20client_20architecture_34',['Network Wrapper Server and Network Wrapper Client Architecture',['../group__nws__and__nwc__architecture.html',1,'']]],
  ['and_20visualizing_20yarp_20network_35',['yarpviz: a graphical tool for profiling and visualizing YARP network',['../group__yarpviz.html',1,'']]],
  ['application_36',['yarpdataplayer example application',['../group__yarpdataplayer__example.html',1,'']]],
  ['applications_20for_20yarpdatadumper_37',['yarpdatadumperAppGenerator: Generate yarpmanager applications for yarpdatadumper',['../group__yarpdatadumperAppGenerator.html',1,'']]],
  ['arbitrating_20multiple_20connections_38',['An example of using port monitors for arbitrating multiple connections',['../group__portmonitors__examples__1.html',1,'']]],
  ['arbitrator_20with_20time_20events_39',['An example of using port arbitrator with time events',['../group__portmonitors__examples__2.html',1,'']]],
  ['architecture_40',['architecture',['../group__dev__impl__network__clients.html',1,'Network Clients (Clients - pre NWC/NWS architecture)'],['../group__dev__impl__wrapper.html',1,'Network Servers (Wrappers - pre NWC/NWS architecture)'],['../group__nws__and__nwc__architecture.html',1,'Network Wrapper Server and Network Wrapper Client Architecture']]],
  ['as_20specified_20in_20an_20xml_20file_41',['yarprobotinterface: Start multiple YARP devices as specified in an xml file.',['../group__yarprobotinterface.html',1,'']]],
  ['at_20the_20both_20sides_20of_20a_20connection_20to_20encode_20and_20decode_20data_42',['An example of using the portmonitor object at the both sides of a connection to encode and decode data',['../group__portmonitors__examples__3.html',1,'']]],
  ['audio_20device_43',['yarpaudiocontrolgui: Controls the playback/recording of an audio device',['../group__yarpaudiocontrolgui.html',1,'']]],
  ['audio_20in_20yarp_44',['Audio in YARP',['../group__AudioDoc.html',1,'']]],
  ['audio_20streams_45',['yarphear: listen to YARP audio streams',['../group__yarphear.html',1,'']]],
  ['available_20carriers_46',['Available Carriers',['../group__carriers__lists.html',1,'']]],
  ['available_20portmonitors_47',['Available Portmonitors',['../group__portmonitors__lists.html',1,'']]]
];
