var searchData=
[
  ['raw_20motor_20interfaces_0',['Raw Motor Interfaces',['../group__dev__iface__motor__raw.html',1,'']]],
  ['raw_20version_1',['Other Device Interfaces (Raw version)',['../group__dev__iface__other__raw.html',1,'']]],
  ['read_20audio_20files_20from_20disk_20and_20sends_20them_20to_20the_20network_2',['yarpAudioPlayer: read audio files from disk and sends them to the network',['../group__yarpAudioPlayer.html',1,'']]],
  ['recorded_20data_3',['yarpdataplayer: replay recorded data',['../group__yarpdataplayer.html',1,'']]],
  ['recorder_4',['yarpdatadumper: the YARP data recorder',['../group__yarpdatadumper.html',1,'']]],
  ['recording_20example_5',['yarpdataplayer recording example',['../group__yarpdataplayer__rec__example.html',1,'']]],
  ['recording_20of_20an_20audio_20device_6',['yarpaudiocontrolgui: Controls the playback/recording of an audio device',['../group__yarpaudiocontrolgui.html',1,'']]],
  ['related_20functionalities_7',['yarp::os OS-related functionalities',['../group__os__module.html',1,'']]],
  ['remappers_8',['Remappers',['../group__dev__impl__remappers.html',1,'']]],
  ['replay_20recorded_20data_9',['yarpdataplayer: replay recorded data',['../group__yarpdataplayer.html',1,'']]],
  ['replay_20robot_20movements_10',['yarpactionsplayer: an utility to replay robot movements',['../group__yarpactionsplayer.html',1,'']]],
  ['required_20devices_20needed_20for_20transforming_20frames_11',['FrameTransform: start all the required devices needed for transforming frames',['../group__FrameTransform.html',1,'']]],
  ['rerun_20io_12',['yarpRerun: log data of a yarp port to rerun.io',['../group__yarpRerun.html',1,'']]],
  ['robot_13',['robot',['../group__yarpmobilebasegui.html',1,'yarpmobilebasegui: Control the mobile base of the robot'],['../group__yarpmotorgui.html',1,'yarpmotorgui: move the joints of a robot']]],
  ['robot_20movements_14',['yarpactionsplayer: an utility to replay robot movements',['../group__yarpactionsplayer.html',1,'']]],
  ['robotinterface_20library_15',['yarp::robotinterface YARP RobotInterface library',['../group__robointerface__all.html',1,'']]],
  ['robotinterface_20xml_20files_16',['YARP robotinterface XML files',['../group__yarp__robotinterface__xml__config__files.html',1,'']]],
  ['ros_20network_20wrapper_20clients_20nwc_17',['ROS Network Wrapper Clients (NWC)',['../group__dev__impl__nwc__ros.html',1,'']]],
  ['ros_20network_20wrapper_20servers_20nws_18',['ROS Network Wrapper Servers (NWS)',['../group__dev__impl__nws__ros.html',1,'']]],
  ['ros2_20network_20wrapper_20clients_20nwc_19',['ROS2 Network Wrapper Clients (NWC)',['../group__dev__impl__nwc__ros2.html',1,'']]],
  ['ros2_20network_20wrapper_20servers_20nws_20',['ROS2 Network Wrapper Servers (NWS)',['../group__dev__impl__nws__ros2.html',1,'']]],
  ['run_20and_20manage_20multiple_20programs_20on_20a_20set_20of_20machines_21',['run and manage multiple programs on a set of machines',['../group__yarpmanager-console.html',1,'yarpmanager-console: run and manage multiple programs on a set of machines'],['../group__yarpmanager.html',1,'yarpmanager: edit, run and manage multiple programs on a set of machines']]],
  ['run_20programs_20on_20a_20set_20of_20machines_22',['yarprun: run programs on a set of machines',['../group__yarprun.html',1,'']]]
];
