var searchData=
[
  ['c_20and_20dlls_20to_20modify_20incoming_20data_20in_20an_20input_20port_0',['An example which shows how to use C++ and DLLS to modify incoming data in an input port',['../group__portmonitors__examples__5.html',1,'']]],
  ['carrier_1',['Gstreamer carrier',['../group__carrier__gstreamer__howto.html',1,'']]],
  ['carriers_2',['carriers',['../group__carriers__lists.html',1,'Available Carriers'],['../group__carriers__module.html',1,'Carriers'],['../group__carrier__config__mpi.html',1,'mpi carriers']]],
  ['carriers_20for_20new_20kinds_20of_20connections_3',['Creating carriers for new kinds of connections',['../group__carrier__expert.html',1,'']]],
  ['check_20yarp_20configuration_4',['yarp-config: utility to check yarp configuration',['../group__yarp-config.html',1,'']]],
  ['classes_5',['classes',['../group__key__class.html',1,'Basic Classes'],['../group__comm__class.html',1,'Communication Classes'],['../group__sig__class.html',1,'yarp::sig  classes']]],
  ['client_20architecture_6',['Network Wrapper Server and Network Wrapper Client Architecture',['../group__nws__and__nwc__architecture.html',1,'']]],
  ['client_20configurations_7',['FrameTransform: possibile server-client configurations',['../group__Fts__ftc__config.html',1,'']]],
  ['clients_20clients_20pre_20nwc_20nws_20architecture_8',['Network Clients (Clients - pre NWC/NWS architecture)',['../group__dev__impl__network__clients.html',1,'']]],
  ['clients_20nwc_9',['clients nwc',['../group__dev__impl__nwc__ros.html',1,'ROS Network Wrapper Clients (NWC)'],['../group__dev__impl__nwc__ros2.html',1,'ROS2 Network Wrapper Clients (NWC)'],['../group__dev__impl__nwc__yarp.html',1,'YARP Network Wrapper Clients (NWC)']]],
  ['code_20generator_20compiler_20for_20parameters_20parsers_10',['yarpDeviceParamParserGenerator: YARP code generator/compiler for parameters parsers',['../group__yarpDeviceParamParserGenerator.html',1,'']]],
  ['code_20generator_20compiler_20for_20thrift_20idl_11',['yarpidl_thrift: YARP code generator/compiler for Thrift IDL',['../group__yarpidl__thrift.html',1,'']]],
  ['command_20line_20interface_12',['yarp: the main command-line interface',['../group__yarp.html',1,'']]],
  ['communication_20classes_13',['Communication Classes',['../group__comm__class.html',1,'']]],
  ['compile_20yarp_20plugins_14',['Ways to compile YARP plugins',['../group__yarp__plugins.html',1,'']]],
  ['compiler_20for_20parameters_20parsers_15',['yarpDeviceParamParserGenerator: YARP code generator/compiler for parameters parsers',['../group__yarpDeviceParamParserGenerator.html',1,'']]],
  ['compiler_20for_20thrift_20idl_16',['yarpidl_thrift: YARP code generator/compiler for Thrift IDL',['../group__yarpidl__thrift.html',1,'']]],
  ['config_3a_20utility_20to_20check_20yarp_20configuration_17',['yarp-config: utility to check yarp configuration',['../group__yarp-config.html',1,'']]],
  ['configuration_18',['configuration',['../group__dev__class.html',1,'Device Creation/Configuration'],['../group__yarp-config.html',1,'yarp-config: utility to check yarp configuration']]],
  ['configurations_19',['FrameTransform: possibile server-client configurations',['../group__Fts__ftc__config.html',1,'']]],
  ['configuring_20yarp_20connections_20',['Configuring YARP Connections',['../group__carrier__config.html',1,'']]],
  ['connection_20to_20encode_20and_20decode_20data_21',['An example of using the portmonitor object at the both sides of a connection to encode and decode data',['../group__portmonitors__examples__3.html',1,'']]],
  ['connections_22',['connections',['../group__portmonitors__examples__1.html',1,'An example of using port monitors for arbitrating multiple connections'],['../group__carrier__config.html',1,'Configuring YARP Connections'],['../group__carrier__expert.html',1,'Creating carriers for new kinds of connections'],['../group__yarpconnectionsinfo.html',1,'yarpconnectionsinfo: A tool to display YARP ports and connections']]],
  ['console_23',['yarp: yarpdataplayer-console',['../group__yarpdataplayer-console.html',1,'']]],
  ['console_3a_20run_20and_20manage_20multiple_20programs_20on_20a_20set_20of_20machines_24',['yarpmanager-console: run and manage multiple programs on a set of machines',['../group__yarpmanager-console.html',1,'']]],
  ['console_3a_20visualize_20log_20from_20yarp_20programs_25',['yarplogger-console: visualize log from YARP programs',['../group__yarplogger-console.html',1,'']]],
  ['content_20of_20a_20port_26',['yarpscope: visualize the numerical content of a port',['../group__yarpscope.html',1,'']]],
  ['control_20the_20mobile_20base_20of_20the_20robot_27',['yarpmobilebasegui: Control the mobile base of the robot',['../group__yarpmobilebasegui.html',1,'']]],
  ['controls_20a_20llm_20device_28',['yarpllmgui: Controls a LLM device',['../group__yarpllmgui.html',1,'']]],
  ['controls_20the_20playback_20recording_20of_20an_20audio_20device_29',['yarpaudiocontrolgui: Controls the playback/recording of an audio device',['../group__yarpaudiocontrolgui.html',1,'']]],
  ['create_20a_20new_20data_20type_20in_20a_20port_30',['An example which shows how to use a Lua script to create a new data type in a port',['../group__portmonitors__examples__7.html',1,'']]],
  ['creating_20carriers_20for_20new_20kinds_20of_20connections_31',['Creating carriers for new kinds of connections',['../group__carrier__expert.html',1,'']]],
  ['creation_20configuration_32',['Device Creation/Configuration',['../group__dev__class.html',1,'']]]
];
